POST http://localhost/login
Content-Type: application/json

{
  "email": "sidikov.marsel@gmail.com",
  "password": "qwerty007"
}

###

GET http://localhost:80/teachers
X-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwicm9sZSI6IkFETUlOIiwic3RhdGUiOiJBQ1RJVkUiLCJlbWFpbCI6InNpZGlrb3YubWFyc2VsQGdtYWlsLmNvbSJ9.G7KEa3UgF0wmfAa_O61-hU7n4f16YAxvDOnGuDBRDyw



###

POST http://localhost/teachers
Content-Type: application/json

{
  "firstName": "Марсель",
  "lastName": "Сидиков"
}

###

POST http://localhost/teachers
Content-Type: application/json

{
  "firstName": "Михаил",
  "lastName": "Абрамский"
}

###

PUT http://localhost/teachers/1
Content-Type: application/json

{
  "firstName": "Марсель",
  "lastName": "Ситдиков"
}

###

DELETE http://localhost/teachers/1

###

GET http://localhost:8080/courses

###

POST http://localhost/courses
Content-Type: application/json

{
  "title": "Информатика"
}

###

POST http://localhost/courses/1/teachers
Content-Type: application/json

{
  "id": 1
}

###

POST http://localhost/users
Content-Type: application/json

{
  "email": "aferenetz@kpfu.ru",
  "firstName": "Александр",
  "lastName": "Ференец",
  "id": 10
}

###